name: Java Build and Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout only required directory
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          examples/codeql/**
        sparse-checkout-cone-mode: false

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Generate pom.xml if missing
      run: |
        if [ ! -f "pom.xml" ]; then
          echo "Generating sample Maven project..."
          mvn archetype:generate \
            -DgroupId=com.example \
            -DartifactId=myapp \
            -DarchetypeArtifactId=maven-archetype-quickstart \
            -DinteractiveMode=false

          mv myapp/* . && mv myapp/.* . 2>/dev/null || true
          rm -rf myapp
        fi

    - name: Build and package JAR
      run: |
        echo "Building project and creating JAR file..."
        mvn clean package

    - name: List JAR file(s) created
      run: |
        echo "Showing contents of target/ directory:"
        ls -lh target/*.jar || echo "No JAR file found."
